module.exports = {
  JWT_EXPIRATION: "JWT token has expired, please login to obtain a new one",
  USE_VALID_TOKEN: "Something went wrong, Please use valid token",
  AUTH_HEADER: "Authorization not passed in the headers",
  SOMETHING_WRONG: "Something went wrong",
  ACCESS_DENIED: "Access denied",
  ROLE_PRODUCT_ADMIN: "ROLE_PRODUCT_ADMIN",
  ROLE_BASIC: "ROLE_BASIC",
  ROLE_CONSUMER: "ROLE_CONSUMER",
  SUCCESS: "All the data fetched successfully",
  GET: "get",
  POST: "post",
  UPDATE: "patch",
  DELETE: "delete",
  ALL_CONFIG_DATA: "It should GET all the Config data",
  TESTUSER: "TESTUSER",
  SUCCESS: "All the data fetched successfully",
  FAILURE: "It should NOT GET all the Config data",
  BRAND: "brand",
  BRAND_SUCCESS_TEST_CASE: "It should GET all the Brand data",
  BRAND_FAILURE_TEST_CASE: "It should NOT GET all the Brand data",
  CONFIG_FAILURE_ENDPOINT: "confi",
  BRAND_FAILURE_ENDPOINT: "bran",
  ROLE: "Role",
};
